### ISSUE TITLE
Fail to reset MySQL native password

### ISSUE THREAD

**Issue by FrancescoBorzi** [azerothcore/acore-docker#2] opened 2022-01-02 07:24 UTC
Since MySQL 8.0 there is a new authentication mechanism by default that prevents some apps from logging in (see https://github.com/mysqljs/mysql/issues/1507 for nodejs-based apps for example). 

This affects Keira3 as well. This is a known issue and the solution is usually simple (see https://stackoverflow.com/q/65271160/3497671 ), just reset the password using `mysql_native_password` :

```sql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
```

However in acore-docker this solution DOES NOT WORK. The query is executed without errors, but password doesn't get reset and the error persists.

I've tried by running the query from both HeidiSQL as well as directly from the MySQL server console using the bash command line inside the docker container, nothing worked.

**Comment by FrancescoBorzi** [comment] 2022-01-02 07:24
@Yehonal as this prevents acore-docker users from using Keira3, it's quite critical. Can you please have a look at it?

**Comment by gr33k** [comment] 2022-11-02 01:02
I also am running into this issue when trying to use https://github.com/masterking32/WoWSimpleRegistration

Do we have a solution for this problem? Thank you

**Comment by Helias** [comment] 2022-11-02 11:33
The issue is related to the mysql client of the application.

We recently updated the mysql library inside Keira3 for the new version 3.4.3, so if someone runs the acore-docker using `docker-compose up` with the development versionof Keira3-3.4.3 it is possible to connect to the database using

host: `localhost`
port: `63306`
username: `root`
password: `password` (if you do not change it, it's `password` the default one)
database: `acore_world`

![image](https://user-images.githubusercontent.com/519778/199479470-283f12d4-bfbb-46a8-af80-b0c41210bce5.png)


I am closing this issue because it does not depend properly on acore-docker

**Closed as completed by Helias** 2022-11-02 11:33 UTC

**Comment by Yehonal** [comment] 2022-11-02 18:00
GJ!!
